version: '3'

services:
  postgres:
    image: postgres:15-alpine 
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_PORT: 5432 
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres
      PGUSER: postgres_user
      PGPASSWORD: postgres_password
      PGPORT: 5432 
      PGHOST: localhost
      PGDATABASE: postgres
    ports:
      - "9999:5432"
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/code
    privileged:
      true

volumes:
  postgres_data:
